name: Run Scrapy and Upload to GCS

on:
  push:
    branches:
      - main

jobs:
  run-scrapy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        spider: [zara-store, Asosstore-spider, localstore-spider]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create and Activate Virtual Environment
        run:
          cd .\StoreData\
          python -m venv venv  
          source venv/Scripts/activate

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install scrapy
          pip install pillow
          pip install scrapy-splash
          pip install -r requirements.txt || true
          

      - name: Run Scrapy spiders
        run: scrapy crawl ${{ matrix.spider }} -o ${{ matrix.spider }}.csv -s DOWNLOAD_FAIL_ON_DATALOSS=False

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.spider }}-output
          path: ${{ matrix.spider }}.csv
